### ISSUE TITLE
Unable to build locally on mac

### ISSUE THREAD

**Issue by jainendra** [conwnet/github1s#242]
Following steps for local development here - https://github.com/conwnet/github1s#local-development
`yarn` went fine
`yarn watch` is failing

``` jai@mac github1s % yarn watch
yarn run v1.22.10
$ rm -rf dist && run-p watch:*
$ ./scripts/watch.sh
$ cd lib/vscode && yarn watch
$ cd extensions/github1s && yarn dev
$ cd scripts/watch && node watch-src.js
$ cd scripts/watch && node watch-dist.js
copy resources done!
rsync: link_stat "/Users/jai/gitlab1s/github1s/lib/vscode/node_modules/vscode-textmate" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
error Command failed with exit code 23.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "watch:setup" exited with 23.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

OS: macOS 11.2 Big Sur

**Comment by xcv58** [comment]
Could you please run `yarn clean`, `yarn`, `yarn build` to see whether it could build on your machine?

If it could build successfully, you can try `yarn watch` again to see whether it works.

**Comment by jainendra** [comment]
@xcv58 I did run 
`yarn clean`, `yarn`, `yarn build`
Still getting the same error

**Comment by conwnet** [comment]
@jainendra Is the `yarn` command working fine?
after `yarn` command, there should be a `lib/vscode` and the `lib/vscode/node_modules` directory in the project.

**Comment by jainendra** [comment]
@conwnet I can see `lib/vscode` but not the `lib/vscode/node_modules`. I also don't see any error in yarn apart from a lot of warnings - `warning dart-code@3.20.0-dev: The engine "vscode" appears to be invalid.`

**Comment by conwnet** [comment]
@jainendra
> I can see lib/vscode but not the lib/vscode/node_modules

So I think there should some errors during installing dependencies, you can try to install the vscode dependencies manually, and check what's wrong here
~~~
cd lib/vscode
yarn
~~~
I think the [prerequisites](https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites) maybe not ready, Or there is a Rate Limited error during install the vscode dependencies

**Comment by jainendra** [comment]
@conwnet Let me try this. Can you also point me to a file where i can run each command manually and see what's breaking ?

Also any chance you are thinking of pushing a pre built image to docker hub ? So that it's easy for someone who just want to try it out locally and then start development right away ?

**Comment by conwnet** [comment]
> Can you also point me to a file where i can run each command manually and see what's breaking ?

@jainendra The full build/dev scripts you can find in the `/scripts` directory. I think the you can try to build the vscode manually to see if it works.

> Also any chance you are thinking of pushing a pre built image to docker hub ? So that it's easy for someone who just want to try it out locally and then start development right away ?

Thanks you for the good idea, we will do it next❤️

**Comment by jainendra** [comment]
@conwnet Would love to help you out with creating a dev docker image. Let me know how i can contribute. 

I got the problem. I think this is creating issue. 

```
git clone --depth 1 -b 1.52.1 https://github.com/microsoft/vscode.git vscode
```
```
Cloning into 'vscode'...
remote: Enumerating objects: 6163, done.
remote: Counting objects: 100% (6163/6163), done.
remote: Compressing objects: 100% (5218/5218), done.
remote: Total 6163 (delta 832), reused 3946 (delta 393), pack-reused 0
Receiving objects: 100% (6163/6163), 11.84 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (832/832), done.
Note: switching to 'ea3859d4ba2f3e577a159bc91e3074c5d85c0523'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

error: unable to create file extensions/vscode-notebook-tests/src/typings/ref.d.ts: Interrupted system call
Updating files: 100% (4699/4699), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
Any reason why we are not cloning it as it is ?

**Comment by xcv58** [comment]
There is way to develop with docker. Could you please try this https://github.com/conwnet/github1s#-or--vs-code--docker-development ?

**Comment by jainendra** [comment]
@xcv58 I did try that out things that are broken on mac worked in dev container but then `vscode/out` folder is not being generated hence I am getting error in `autoSyncVscodeOut` inside `watch-dist.js` when i m running `yarn watch`

Any further guidance would be really helpful

**Comment by xcv58** [comment]
Did `yarn build` work?

**Comment by jainendra** [comment]
@xcv58 I tried `yarn build` in github1s dev container but it's failing due to - `Error: compilation requires 4GB of RAM` ? How do we increase memory limit for a dev container. I am going through the docs didn't find it yet

As for mac I was stuck at cloning the proper repo for vscode. I am trying it now `yarn build`

**Comment by jainendra** [comment]
@xcv58 @conwnet Don't know what i did and in what order but atleast vscode is now loading locally - I can fiddle around with it now *phew*. 
Essentially what i faced issue was with - `git clone --depth 1 -b 1.52.1 https://github.com/microsoft/vscode.git vscode` in `postinstall.sh`.
I had to manually clone it and do `yarn` inside it. Not sure why but clone is somehow failing.
Then `yarn watch` is not working so i tried `yarn build` + I don't remember what i did in between. 

So if anyone else is facing issue on mac BigSur. Above steps might help. Let me see if it actually is working as expected.

**Comment by conwnet** [comment]
> Essentially what i faced issue was with - `git clone --depth 1 -b 1.52.1 https://github.com/microsoft/vscode.git vscode` in `postinstall.sh`.

you can clone the full vscode repo and run `git checkout 1.52.1` then.

Can you build the original vscode successfully?

It seems we should provide an prebuilt vscode quickily.

**Comment by jainendra** [comment]
@conwnet I did the same. I cloned the vscode repo, switched to `1.52.1` and built it. I am not sure if it was successful since there was no `out` folder which is required to build `github1s`. I did this in dev container but i wasn't able to run it.

Yes, if you can provide a prebuild vscode that would be great.

`In summary building vscode is an issue` which is causing problem with `yarn watch`

After doing the same for mac, I tried running `yarn build` and it worked. I am not sure how can i test my changes frequently i m assuming i'll have to run `yarn build` again.

**Comment by jainendra** [comment]
@xcv58 @conwnet Also running `yarn build` in dev container raises this
```
node ➜ /workspaces/github1s (master ✗) $ yarn build
yarn run v1.22.5
$ ./scripts/build.sh
$ gulp --max_old_space_size=8192 compile-build
[16:25:19] Node flags detected: --max_old_space_size=8192
[16:25:19] Respawned to PID: 411
[16:25:23] Using gulpfile /workspaces/github1s/lib/vscode/gulpfile.js
[16:25:23] Starting 'compile-build'...
[16:25:23] Starting clean-out-build ...
[16:25:23] Finished clean-out-build after 4 ms
[16:25:23] Starting compile-build ...
[16:25:23] 'compile-build' errored after 10 ms
[16:25:23] Error: compilation requires 4GB of RAM
    at /workspaces/github1s/lib/vscode/build/lib/compilation.js:74:19
    at /workspaces/github1s/lib/vscode/build/lib/task.js:45:28
    at new Promise (<anonymous>)
    at _doExecute (/workspaces/github1s/lib/vscode/build/lib/task.js:34:12)
    at _execute (/workspaces/github1s/lib/vscode/build/lib/task.js:25:11)
    at compile-build (/workspaces/github1s/lib/vscode/build/lib/task.js:64:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by xcv58** [comment]
@jainendra we published a prebuilt VS Code in https://github.com/conwnet/github1s/pull/265. You should not have the same issue if you follow the new instruction in the README https://github.com/conwnet/github1s#local-development

**Comment by mecirmartin** [comment]
I have the very same problem, i followed instructions on local development with full vscode build, still getting ```node:child_process:333
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: rsync -a /Users/martinmecir/Desktop/tryout/github1s/vscode-web-github1s/lib/vscode/out/ /Users/martinmecir/Desktop/tryout/github1s/dist/static/vscode
rsync: link_stat "/Users/martinmecir/Desktop/tryout/github1s/vscode-web-github1s/lib/vscode/out/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]```
when running `yarn watch-with-vscode`

**Comment by xcv58** [comment]
> I have the very same problem, i followed instructions on local development with full vscode build, still getting
> 
> ```
> node:child_process:333
>       ex = new Error('Command failed: ' + cmd + '\n' + stderr);
>            ^
> 
> Error: Command failed: rsync -a /Users/martinmecir/Desktop/tryout/github1s/vscode-web-github1s/lib/vscode/out/ /Users/martinmecir/Desktop/tryout/github1s/dist/static/vscode
> rsync: link_stat "/Users/martinmecir/Desktop/tryout/github1s/vscode-web-github1s/lib/vscode/out/." failed: No such file or directory (2)
> rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
> ```
> 
> when running `yarn watch-with-vscode`

Does normal `yarn watch` work for you?

**Comment by mecirmartin** [comment]
@jainendra  @xcv58  
Yes, normal yarn watch works fine 

Upon further investigation i found out how to successfully run `yarn watch-with-vscode`
It errors out because it can't find `vscode-web-github1s/lib/vscode/out`
However if i run
```
cd vscode-web-github1s/lib/vscode
yarn gulp compile-web
yarn watch
```
The folder `vscode-web-github1s/lib/vscode/out` will be created. Then just run these commands (as stated in docs)
```
yarn build:vscode 
yarn watch-with-vscode
```

No idea what is causing this, if there is solution, let me know, i could submit PR

**Comment by JeffreyBool** [comment]
建议把前置依赖环境打包成 docker 镜像，前置条件太难解决了

**Comment by mecirmartin** [comment]
> 建议把前置依赖环境打包成 docker 镜像，前置条件太难解决了

Please use english in public, open source repositories

**Comment by JeffreyBool** [comment]
It is suggested to package the pre dependent environment as a docker image. The pre condition is too difficult to solve
